import Head from "next/head";
import { RootLayout } from "../components/Layout";
import { EmployerTable } from "@/components/EmployerTable";
import {
  Heading,
  Modal,
  ModalContent,
  ModalOverlay,
  Stack,
} from "@chakra-ui/react";
import {
  Dispatch,
  SetStateAction,
  createContext,
  useRef,
  useState,
} from "react";
import { Employer } from "@/types/Employer";
import { ModalTypes } from "@/types/Modals";
import { getDashboardModal } from "@/components/Modals";

interface IDashboardModal {
  isOpen: boolean;
  modalType: ModalTypes;
  employee: Employer | undefined;
}
interface IHomeContext {
  dashboardModal: IDashboardModal;
  setDashboardModal: Dispatch<SetStateAction<IDashboardModal>>;
}

const defaultModalState = {
  isOpen: false,
  modalType: ModalTypes.ADD_EMPLOYER,
  employee: undefined,
};

export const HomeContext = createContext<IHomeContext>({
  dashboardModal: defaultModalState,
  setDashboardModal: () => {},
});

export const HomeModals = {};
export default function Home() {
  const [dashboardModal, setDashboardModal] =
    useState<IDashboardModal>(defaultModalState);
  const finalRef = useRef(null);
  return (
    <>
      <Head>
        <title>React Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootLayout navbarText="Dashboard App">
        <HomeContext.Provider
          value={{
            dashboardModal: dashboardModal,
            setDashboardModal: setDashboardModal,
          }}
        >
          <Stack spacing={5}>
            <Heading as="h2" size="lg">
              Boa noite! 👋🏼
            </Heading>
            <EmployerTable />
          </Stack>
          <Modal
            finalFocusRef={finalRef}
            isOpen={dashboardModal.isOpen}
            onClose={() => setDashboardModal(defaultModalState)}
          >
            <ModalOverlay />
            <ModalContent>
              {getDashboardModal(dashboardModal.modalType)}
            </ModalContent>
          </Modal>
        </HomeContext.Provider>
      </RootLayout>
    </>
  );
}
