import Head from "next/head";
import AppSidebar from "./components/Sidebar";
import { RootLayout } from "./components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootLayout navbarText="Dashboard App">
        <p>Dashboard</p>
      </RootLayout>
    </>
  );
}
